// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOz9nIKqKMVSeO8UOPS9qgSFLKVmQjPQQ',
    appId: '1:844435826304:web:e00a6e2e2c07db93c8e865',
    messagingSenderId: '844435826304',
    projectId: 'todo-app-af095',
    authDomain: 'todo-app-af095.firebaseapp.com',
    storageBucket: 'todo-app-af095.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5YJgVN-shqDTA40wBjnzjYWi3l_Mp2DM',
    appId: '1:844435826304:android:5889bd857f70216dc8e865',
    messagingSenderId: '844435826304',
    projectId: 'todo-app-af095',
    storageBucket: 'todo-app-af095.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBR5qiF2u_DGVkfQROYjtWOLcFK4s0knM',
    appId: '1:844435826304:ios:8f3ec007fe755bcfc8e865',
    messagingSenderId: '844435826304',
    projectId: 'todo-app-af095',
    storageBucket: 'todo-app-af095.appspot.com',
    iosBundleId: 'com.example.secondTaskTodoListapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBR5qiF2u_DGVkfQROYjtWOLcFK4s0knM',
    appId: '1:844435826304:ios:8f3ec007fe755bcfc8e865',
    messagingSenderId: '844435826304',
    projectId: 'todo-app-af095',
    storageBucket: 'todo-app-af095.appspot.com',
    iosBundleId: 'com.example.secondTaskTodoListapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOz9nIKqKMVSeO8UOPS9qgSFLKVmQjPQQ',
    appId: '1:844435826304:web:27c9d1a22cb9fc5dc8e865',
    messagingSenderId: '844435826304',
    projectId: 'todo-app-af095',
    authDomain: 'todo-app-af095.firebaseapp.com',
    storageBucket: 'todo-app-af095.appspot.com',
  );
}
